/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import copiaPeliculas.mainC;
import copiaPeliculas.ArchivoClase;
import copiaPeliculas.Equipos;
import copiaPeliculas.FitnessMundial;
import copiaPeliculas.MundialFitness;
import dao.DaoEquipos;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import org.jgap.Configuration;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author Freddy
 */
public class mundial extends javax.swing.JDialog {

    public List<Equipos> s = new ArrayList<Equipos>();
    MundialFitness pp = new MundialFitness();

    /**
     * Creates new form mundial
     */
    public mundial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        cbxEquipos = new javax.swing.JComboBox();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRanknfFifa = new javax.swing.JTextField();
        txtGrupoPertenece = new javax.swing.JTextField();
        txtCopasGanadas = new javax.swing.JTextField();
        txtPartidoultimo = new javax.swing.JTextField();
        txtpartidoPenultimo = new javax.swing.JTextField();
        txtTrasantepenultmi = new javax.swing.JTextField();
        txtNombreEquipo = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaChromosome = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        btnCalcular = new javax.swing.JButton();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jLabel5 = new javax.swing.JLabel();
        txtValosFitnes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtvalorchromosome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNDIAL 2014");
        setUndecorated(true);
        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mundial.jpg"))); // NOI18N

        cbxEquipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brazil", "Croacia", "Mexico ", "Camerun", "Espania", "Paises Bajos", "Chile ", "Australia", "Colombia", "Grecia", "Costa de Marfil", "Japon", "Uruguay", "Costa Rica", "Inglaterra ", "Italia", "Suiza", "Ecuador", "Francia", "Honduras", "Argentina", "Bosnia y Herzegovina", "Iran", "Nigeria", "Alemania", "Portugal", "Ghana", "EEUU", "Belgica", "Argelia", "Rusia", "Republica de Corea" }));
        cbxEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEquiposActionPerformed(evt);
            }
        });

        panelImage2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 18), new java.awt.Color(153, 204, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ranking FIFA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Grupo al que pertenece:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Copas Ganadas:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Resultados 3 ultimos partidos:");

        txtRanknfFifa.setEditable(false);

        txtGrupoPertenece.setEditable(false);

        txtCopasGanadas.setEditable(false);

        txtPartidoultimo.setEditable(false);

        txtpartidoPenultimo.setEditable(false);

        txtTrasantepenultmi.setEditable(false);

        txtNombreEquipo.setEditable(false);
        txtNombreEquipo.setBackground(new java.awt.Color(225, 221, 221));
        txtNombreEquipo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txtNombreEquipo.setForeground(new java.awt.Color(244, 166, 24));

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelImage2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreEquipo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelImage2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpartidoPenultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrasantepenultmi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRanknfFifa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrupoPertenece, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPartidoultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCopasGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreEquipo)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRanknfFifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrupoPertenece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCopasGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPartidoultimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpartidoPenultimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTrasantepenultmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtGrupoPertenece.getAccessibleContext().setAccessibleDescription("");

        btnEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnEditar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconobalon.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconobalon.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 153, 153));
        btnSalir.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconobalon.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setSelected(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${obssocio}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${grupo}"));
        columnBinding.setColumnName("Grupo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ranking}"));
        columnBinding.setColumnName("Ranking");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numCopas}"));
        columnBinding.setColumnName("Numero de Copas");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partido1}"));
        columnBinding.setColumnName("Partido 1");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partido2}"));
        columnBinding.setColumnName("Partido 2");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partido3}"));
        columnBinding.setColumnName("Partido 3");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(jTable1);

        txtaChromosome.setColumns(20);
        txtaChromosome.setRows(5);
        jScrollPane4.setViewportView(txtaChromosome);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${obssocio1}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabla2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${grupo}"));
        columnBinding.setColumnName("Grupo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numCopas}"));
        columnBinding.setColumnName("Número de Copas");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ranking}"));
        columnBinding.setColumnName("Ranking");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partido1}"));
        columnBinding.setColumnName("Partido 1");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partido2}"));
        columnBinding.setColumnName("Partido 2");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partido3}"));
        columnBinding.setColumnName("Partido 3");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane5.setViewportView(tabla2);
        tabla2.getColumnModel().getColumn(2).setResizable(false);
        tabla2.getColumnModel().getColumn(3).setResizable(false);

        btnCalcular.setBackground(new java.awt.Color(153, 153, 153));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconobalon.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        panelImage3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Evolución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 18), new java.awt.Color(51, 255, 0))); // NOI18N
        panelImage3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Valor Fitnes:");

        txtValosFitnes.setEnabled(false);
        txtValosFitnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValosFitnesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Valor  chromosome:");

        txtvalorchromosome.setEnabled(false);
        txtvalorchromosome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorchromosomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelImage3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValosFitnes, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txtvalorchromosome))
                .addContainerGap())
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValosFitnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtvalorchromosome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(cbxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelImage1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)))
                .addGap(21, 21, 21))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)
                                .addGap(14, 14, 14)
                                .addComponent(btnCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addComponent(btnSalir)
                        .addGap(33, 33, 33))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Equipos p = new Equipos();
    private void cbxEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEquiposActionPerformed
        DaoEquipos de = new DaoEquipos();
        if (cbxEquipos.getSelectedIndex() == 0) {
            p = de.nombre("Brasil").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/brasil.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 1) {
            p = de.nombre("Croacia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/croacia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 2) {
            p = de.nombre("Mexico").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/mexico.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 3) {
            p = de.nombre("Camerun").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/camerun.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 4) {
            p = de.nombre("Espania").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/espania.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 5) {
            p = de.nombre("Paises Bajos").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/paisesBajos.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 6) {
            p = de.nombre("Chile").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/chile.gif");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 7) {
            p = de.nombre("Australia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/australia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 8) {
            p = de.nombre("Colombia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/colombia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 9) {
            p = de.nombre("Grecia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/grecia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 10) {
            p = de.nombre("Costa de Marfil").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/costa_de_marfil.png");
            lbl1.setIcon(icono);
        }

        if (cbxEquipos.getSelectedIndex() == 11) {
            p = de.nombre("Japon").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/japon.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 12) {
            p = de.nombre("Uruguay").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/uruguay.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 13) {
            p = de.nombre("Costa Rica").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/costa_rica.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 14) {
            p = de.nombre("Inglaterra").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/inglaterra.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 15) {
            p = de.nombre("Italia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/italia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 16) {
            p = de.nombre("Suiza").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/suiza.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 17) {
            p = de.nombre("Ecuador").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/ecuador.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 18) {
            p = de.nombre("Francia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/francia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 19) {
            p = de.nombre("Honduras").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/honduras.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 20) {
            p = de.nombre("Argentina").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/argentina.gif");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 21) {
            p = de.nombre("Bosnia y Herzegovina").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/Bosnia_y_Herzegovina.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 22) {
            p = de.nombre("Iran").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/iran.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 23) {
            p = de.nombre("Nigeria").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/nigeria.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 24) {
            p = de.nombre("Alemania").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/alemania.jpg");
            lbl1.setIcon(icono);
        }

        if (cbxEquipos.getSelectedIndex() == 25) {
            p = de.nombre("Portugal").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/portugal.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 26) {
            p = de.nombre("Ghana").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/ghana.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 27) {
            p = de.nombre("Estados Unidos").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/estados_inidos.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 28) {
            p = de.nombre("Belgica").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/belgica.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 29) {
            p = de.nombre("Argelia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/argelia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 30) {
            p = de.nombre("Rusia").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/rusia.jpg");
            lbl1.setIcon(icono);
        }
        if (cbxEquipos.getSelectedIndex() == 31) {
            p = de.nombre("Republica de Corea").get(0);
            txtNombreEquipo.setText(p.getNombre());
            txtRanknfFifa.setText(p.getRanking());
            txtGrupoPertenece.setText(p.getGrupo());
            txtPartidoultimo.setText(p.getPartido1());
            txtpartidoPenultimo.setText(p.getPartido2());
            txtTrasantepenultmi.setText(p.getPartido3());
            txtCopasGanadas.setText(p.getNumCopas());
            ImageIcon icono = new ImageIcon(System.getProperty("user.dir") + "/src/imagenes/republica_de_corea.jpg");
            lbl1.setIcon(icono);
        }
    }//GEN-LAST:event_cbxEquiposActionPerformed
    final List<Equipos> e = new ArrayList<>();
    FitnessMundial fm = null;
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        tabla2.removeAll();
        jTable1.removeAll();
        obssocio.clear();
        obssocio1.clear();
        String ssss = "";
        try {
            Configuration.reset();
            MundialFitness test = new MundialFitness();
            test.initialize();
            test.testSelectFittestEquipos();

        } catch (Exception ex) {
            Logger.getLogger(mainC.class.getName()).log(Level.SEVERE, null, ex);
        }
        e.addAll(pp.a);
        obssocio1.addAll(pp.equi16);
        obssocio.addAll(pp.a);
        txtaChromosome.setText("");
        // JOptionPane.showMessageDialog(null, fm.chromos.size());
        txtvalorchromosome.setText("" + fm.chromos.size());
        for (int i = 0; i < fm.chromos.size(); i++) {
            ssss = ssss + " " + fm.chromos.get(i) + "\n";
        }
        txtaChromosome.setText(ssss);
        txtValosFitnes.setText("" + pp.v);
        pp.a.clear();
        pp.equi16.clear();
        fm.chromos.clear();

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtNombreEquipo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Porfavor elija un equipo");
        } else {
            txtCopasGanadas.setEditable(true);
            txtGrupoPertenece.setEditable(true);
            // txtNombreEquipo.setEditable(true);
            txtPartidoultimo.setEditable(true);
            txtRanknfFifa.setEditable(true);
            txtTrasantepenultmi.setEditable(true);
            txtpartidoPenultimo.setEditable(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ArchivoClase a = new ArchivoClase();
        DaoEquipos d = new DaoEquipos();
        if (txtCopasGanadas.getText().equals("") || txtGrupoPertenece.getText().equals("") || txtNombreEquipo.getText().equals("")
                || txtPartidoultimo.getText().equals("") || txtRanknfFifa.getText().equals("") || txtTrasantepenultmi.getText().equals("")
                || txtpartidoPenultimo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar...");

        } else {
            Equipos e = d.nombre(txtNombreEquipo.getText()).get(0);
            d.eliminar(e);
            Equipos ee = new Equipos();
            ee.setGrupo(txtGrupoPertenece.getText());
            ee.setNombre(txtNombreEquipo.getText());
            ee.setNumCopas(txtCopasGanadas.getText());
            ee.setPartido1(txtPartidoultimo.getText());
            ee.setPartido2(txtpartidoPenultimo.getText());
            ee.setPartido3(txtTrasantepenultmi.getText());
            ee.setRanking(txtRanknfFifa.getText());
            d.persistir(ee);
            txtCopasGanadas.setEditable(false);
            txtGrupoPertenece.setEditable(false);
            txtNombreEquipo.setEditable(false);
            txtPartidoultimo.setEditable(false);
            txtRanknfFifa.setEditable(false);
            txtTrasantepenultmi.setEditable(false);
            txtpartidoPenultimo.setEditable(false);
            JOptionPane.showMessageDialog(null, "Se a modificado correctamente..");
            Equipos eq = new Equipos();
            eq = d.nombre(txtNombreEquipo.getText()).get(0);
            txtCopasGanadas.setText(eq.getNumCopas());
            txtGrupoPertenece.setText(eq.getGrupo());
            txtNombreEquipo.setText(eq.getNombre());
            txtPartidoultimo.setText(eq.getPartido1());
            txtRanknfFifa.setText(eq.getRanking());
            txtTrasantepenultmi.setText(eq.getPartido3());
            txtpartidoPenultimo.setText(eq.getPartido2());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        pp.a.clear();
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtValosFitnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValosFitnesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValosFitnesActionPerformed

    private void txtvalorchromosomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorchromosomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorchromosomeActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                mundial dialog = new mundial(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxEquipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private javax.swing.JTable tabla2;
    private javax.swing.JTextField txtCopasGanadas;
    private javax.swing.JTextField txtGrupoPertenece;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtPartidoultimo;
    private javax.swing.JTextField txtRanknfFifa;
    private javax.swing.JTextField txtTrasantepenultmi;
    private javax.swing.JTextField txtValosFitnes;
    private javax.swing.JTextArea txtaChromosome;
    private javax.swing.JTextField txtpartidoPenultimo;
    private javax.swing.JTextField txtvalorchromosome;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    List<Equipos> s2 = new ArrayList<Equipos>();
    ObservableList<Equipos> obssocio = org.jdesktop.observablecollections.ObservableCollections.observableList(s);
    ObservableList<Equipos> obssocio1 = org.jdesktop.observablecollections.ObservableCollections.observableList(s2);

    public ObservableList<Equipos> getObssocio1() {
        return obssocio1;
    }

    public void setObssocio1(ObservableList<Equipos> obssocio1) {
        this.obssocio1 = obssocio1;
    }

    public ObservableList<Equipos> getObssocio() {
        return obssocio;
    }

    public void setObssocio(ObservableList<Equipos> obssocio) {
        this.obssocio = obssocio;
    }

    public JTextArea getTxtaChromosome() {
        return txtaChromosome;
    }

    public void setTxtaChromosome(JTextArea txtaChromosome) {
        this.txtaChromosome = txtaChromosome;
    }
}
